name: UE-IoT-non3GPP CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.7

      - name: Install Go Deps
        run: |
          go mod download
          sudo ln -s $GOROOT /usr/local/go

      - name: Packages Control Plane
        run: |
          sudo apt -y -q update
          sudo apt -y -q install wget git

      - name: Packages User Plane
        run: |
          sudo apt -y update
          sudo apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          go get -u github.com/sirupsen/logrus

      - name: Build
        run: go build -o ue-iot-non3gpp -x ./ue.go

      - name: Test
        run: echo "Implement Test here"
